[default]
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 0
block_timestamp = 0
# NOTE: user need to set bytecodehash='ipfs' for this otherwise verification won't work
# https://github.com/gakonst/foundry/issues/1236 
# https://github.com/gakonst/foundry/pull/1242/files
bytecode_hash = 'ipfs'
cache = true
cache_path = 'cache'
evm_version = 'london'
# output inlined in compiler output
extra_output = []
# output to seperate json file
extra_output_files = []
ffi = false
force = false
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1024
fuzz_runs = 256
gas_limit = 9223372036854775807
gas_price = 0
gas_reports = ['*']
ignored_error_codes = [1878]
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = ['lib']
names = true
no_storage_caching = false
offline = false
optimizer = true
optimizer_runs = 888
out = 'out'
remappings = [
    'clones-with-immutable-args/=lib/clones-with-immutable-args/src/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'solmate/=lib/solmate/src/',
    'splits-contracts/=lib/splits-contracts/contracts/',
]
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
sizes = true
src = 'src'
test = 'test'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
verbosity = 4
via_ir = false

[default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'
